// <auto-generated />
using System;
using EVCS.TriNM.Repositories.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVCS.TriNM.Repositories.Migrations
{
    [DbContext(typeof(EVChargingDBContext))]
    [Migration("20251104025133_RenameTablesToTriNM")]
    partial class RenameTablesToTriNM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.Charger", b =>
                {
                    b.Property<int>("ChargerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChargerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChargerId"));

                    b.Property<string>("ChargerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("StationId")
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    b.HasKey("ChargerId");

                    b.HasIndex("StationId");

                    b.ToTable("ChargerTriNM", (string)null);
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.ChargingTransaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ChargerId")
                        .HasColumnType("int")
                        .HasColumnName("ChargerID");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("EnergyConsumed")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int")
                        .HasColumnName("UserAccountID");

                    b.HasKey("TransactionId");

                    b.HasIndex("ChargerId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("ChargingTransaction", (string)null);
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("PaidDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionID");

                    b.HasKey("PaymentId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CurrentAvailable")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StationId");

                    b.ToTable("StationTriNM", (string)null);
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserAccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAccountId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserAccountId");

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.Charger", b =>
                {
                    b.HasOne("EVCS.TriNM.Repositories.Models.Station", "Station")
                        .WithMany("Chargers")
                        .HasForeignKey("StationId")
                        .IsRequired()
                        .HasConstraintName("FK_Charger_Station");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.ChargingTransaction", b =>
                {
                    b.HasOne("EVCS.TriNM.Repositories.Models.Charger", "Charger")
                        .WithMany("ChargingTransactions")
                        .HasForeignKey("ChargerId")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_Charger");

                    b.HasOne("EVCS.TriNM.Repositories.Models.UserAccount", "UserAccount")
                        .WithMany("ChargingTransactions")
                        .HasForeignKey("UserAccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_User");

                    b.Navigation("Charger");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.Payment", b =>
                {
                    b.HasOne("EVCS.TriNM.Repositories.Models.ChargingTransaction", "Transaction")
                        .WithMany("Payments")
                        .HasForeignKey("TransactionId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Transaction");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.Charger", b =>
                {
                    b.Navigation("ChargingTransactions");
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.ChargingTransaction", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.Station", b =>
                {
                    b.Navigation("Chargers");
                });

            modelBuilder.Entity("EVCS.TriNM.Repositories.Models.UserAccount", b =>
                {
                    b.Navigation("ChargingTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
